name: news
description: Test task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mapster: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.4
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
